import { useState } from "react";
import { trpc } from "@/providers/trpc";
import { useAuth } from "@/hooks/useAuth";
import { IconClose, IconPlane } from "./icons";

const COUNTRIES = ["USA", "Kanada", "Neuseeland", "Großbritannien", "Irland", "Australien", "Japan", "Spanien", "Frankreich", "Anderes Land"] as const;

export function Journals({ onUpgrade }: { onUpgrade: () => void }) {
  const { isAuthenticated, isMember } = useAuth();
  const [open, setOpen] = useState(false);
  const reports = trpc.forum.listTravelReports.useQuery();
  const create = trpc.forum.createTravelReport.useMutation({ onSuccess: async () => { setOpen(false); await reports.refetch(); } });

  const startCreate = () => {
    if (!isAuthenticated || !isMember) { onUpgrade(); return; }
    setOpen(true);
  };

  return <section className="mx-auto max-w-5xl">
    <div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="label-caps mb-3 text-tang">Reiseberichte</p><h1 className="display-xl text-4xl sm:text-5xl">Geschichten, die bleiben</h1><p className="mt-4 max-w-xl text-sm leading-relaxed text-sagedark">Echte Erfahrungen aus der Community – von der ersten Ankunft bis zum letzten Abend.</p></div><button className="btn-tang" onClick={startCreate}>{isMember ? "Bericht schreiben" : "Als Premium schreiben"}</button></div>
    {!isMember && <div className="card-offset mb-6 flex flex-wrap items-center justify-between gap-4 bg-forest p-6 text-cream"><div><p className="font-display text-xl font-bold">Deine Geschichte gehört hierher.</p><p className="mt-1 text-sm text-cream/70">Mit dem Premium-Zugang kannst du eigene Reiseberichte und Bilder veröffentlichen.</p></div><button className="btn-tang" onClick={onUpgrade}>Premium freischalten</button></div>}
    {reports.isLoading ? <div className="card-offset p-8 text-center text-sagedark">Berichte werden geladen …</div> : reports.data?.length ? <div className="grid gap-5 md:grid-cols-2">{reports.data.map((report) => <article key={report.id} className="card-offset overflow-hidden">{report.imageUrl && <img src={report.imageUrl} alt="" className="h-52 w-full object-cover" />}<div className="p-6"><p className="label-caps text-sagedark">{report.country}{report.locationLabel ? ` · ${report.locationLabel}` : ""} · von {report.authorName}</p><h2 className="mt-2 font-display text-2xl font-bold text-forest">{report.title}</h2><p className="mt-4 whitespace-pre-wrap text-sm leading-relaxed text-forest/85">{report.body}</p></div></article>)}</div> : <div className="card-offset p-10 text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-tang/30 text-2xl">✦</div><h2 className="mt-4 font-display text-2xl font-bold text-forest">Noch keine Reiseberichte</h2><p className="mt-2 text-sm text-sagedark">Sei die erste Person und erzähl der Community von deinem Auslandsjahr.</p></div>}
    {open && <ReportDialog onClose={() => setOpen(false)} onSubmit={(input) => create.mutate(input)} pending={create.isPending} />}
  </section>;
}

function ReportDialog({ onClose, onSubmit, pending }: { onClose: () => void; onSubmit: (input: { title: string; body: string; country: (typeof COUNTRIES)[number]; locationLabel?: string; imageBase64?: string; imageName?: string }) => void; pending: boolean }) {
  const [title, setTitle] = useState(""); const [body, setBody] = useState(""); const [country, setCountry] = useState<(typeof COUNTRIES)[number]>("USA"); const [locationLabel, setLocationLabel] = useState(""); const [image, setImage] = useState<{ base64: string; name: string; preview: string } | null>(null); const [error, setError] = useState("");
  const choose = (file: File) => { if (file.size > 4 * 1024 * 1024) { setError("Das Bild darf maximal 4 MB groß sein."); return; } const reader = new FileReader(); reader.onload = () => { const result = String(reader.result); setImage({ base64: result.split(",")[1], name: file.name, preview: result }); }; reader.readAsDataURL(file); };
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-forest/70 p-4" onClick={onClose}><div className="card-offset max-h-[90vh] w-full max-w-2xl overflow-y-auto p-6 sm:p-8" onClick={(event) => event.stopPropagation()}><div className="mb-5 flex items-center justify-between"><h2 className="font-display text-2xl font-bold text-forest">Reisebericht schreiben</h2><button onClick={onClose} aria-label="Schließen"><IconClose className="h-5 w-5" /></button></div><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); if (title.trim() && body.trim().length >= 50) onSubmit({ title, body, country, locationLabel: locationLabel || undefined, imageBase64: image?.base64, imageName: image?.name }); }}><input className="input-line" placeholder="Titel deines Berichts" value={title} onChange={(event) => setTitle(event.target.value)} required minLength={5} /><textarea className="input-line min-h-56 resize-y" placeholder="Erzähl der Community von deinem Erlebnis (mindestens 50 Zeichen) …" value={body} onChange={(event) => setBody(event.target.value)} required minLength={50} /><div className="grid gap-4 sm:grid-cols-2"><select className="input-line" value={country} onChange={(event) => setCountry(event.target.value as (typeof COUNTRIES)[number])}>{COUNTRIES.map((item) => <option key={item}>{item}</option>)}</select><input className="input-line" placeholder="Ort (optional)" value={locationLabel} onChange={(event) => setLocationLabel(event.target.value)} /></div><label className="block cursor-pointer rounded-xl border-2 border-dashed border-forest/25 p-5 text-center text-sm text-sagedark"><input type="file" accept="image/*" className="hidden" onChange={(event) => event.target.files?.[0] && choose(event.target.files[0])} />{image ? <img src={image.preview} alt="Vorschau" className="mx-auto max-h-48 object-cover" /> : "Optional ein Bild hinzufügen (max. 4 MB)"}</label>{error && <p className="text-sm text-red-700">{error}</p>}<div className="flex justify-end gap-2"><button type="button" className="btn-outline" onClick={onClose}>Abbrechen</button><button type="submit" className="btn-tang" disabled={pending || body.trim().length < 50}><IconPlane className="h-4 w-4" />{pending ? "Wird veröffentlicht …" : "Bericht veröffentlichen"}</button></div></form></div></div>;
}
